config/routes.rb
Rails.application.routes.draw do

  root 'billboards#index'
  
  resources :billboards do
    resources :artists
  end

  resources :artists do
    resources :songs
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  belongs_to :billboard
  has_many :songs
end

app/models/billboard.rb
class Billboard < ApplicationRecord
  has_many :artists
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  belongs_to :billboard
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  before_action :set_billboard
  before_action :set_artist, only: (:edit, :update, :destroy, :show)


  def index
    @artist = @billboard.artist
  end

  def show
  end

  def edit
    render partial: 'artists/form'
  end

  def update
    if @artist.update(artist_params)
      redirect to [@billboard, @artist]
    else
      render :new
    end
  end

  def create
    @artist = @billboard.artist.new(artist_params)
    if @artist.save
      rediret_to [@billboard, @artist]
    else
      render :new
    end
  end

  def new
    @artist = @billboard.artist.new
    render partial: 'artists/form'
  end

  def delete
    @artist.destroy
    redirect_to billboards_artists_path
  end
    
    private
    def set_billboard
      @billboard = Billboard.find(params[:billboard_id])
    end

    def set_artist
      @artist = Artist.find(params[:id])
    end

    def artists_params
      params.require(:artist).permist(:name)
    end

end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController

  before_action :find_billboard, only: [:show, :edit, :update, :delete]

  def index
    @billboard = Billboard.all
  end

  def show
  end

  def new
    @billboard = Billboard.new
    render partial: 'form'
  end


  def edit
    render partial: 'form'
  end

  def update
    if @billboard.update(billboard_params)
      redirect_to @billboard
    else 
      render :edit
    end
  end


  def create
    @billboard = Billboard.new(billboard_params)

    if @billboard.save
      redirect_to billboards_path
    else
      render :new
    end
  end

  def delete
    @billboard.destroy
    redirect_to billboards_path
  end

  private
  def billboard_params
    params.required(:billboard).permis(:name)
  end

  def find_billboard
    @billboard = Billboard.find(params[:id])
  end 
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  before_action :set_artist
  before_action :set_song, only: (:edit, :update, :destroy, :show)


  def index
    @song = @artist.songs
  end

  def new
    @songs = Song.new
  end

  def create
    @song = @artist.songs.new(somg_params)
    if @song.save
      redirect_to [@artist, @song]
    else
      render :new
    end
  end

  def edit
    render partial: 'songs/form'
  end

  def show
  end

  def update
    if song.update(song_params)
      redirect_to [@artist, @song]
    else
      render :edit
  end

  def delete
    @song.destroy
    redirect_to artists_songs_path
  end

  private

  def set_artist
    @artist = Artist.find(params[:artist_id])
  end

  def set_song
    @song = Song.find(params[:id])
  end

  def song_params
    params.require(:song).permit(:name)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/create.html.erb
<h1>New Artist</h1>

<%= form_with(model: @artist, local: true, class: 'ui form') do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: 'Artist Nmae' %>
  </div>
  <%= f.submit nil, class: 'ui blue button inverted' %>
<% end %>

app/views/artists/delete.html.erb
<h1>Artists#delete</h1>
<p>Find me in app/views/artists/delete.html.erb</p>

app/views/artists/edit.html.erb
<h1>Artists#edit</h1>
<p>Find me in app/views/artists/edit.html.erb</p>

app/views/artists/index.html.erb
<h1>Artists/h1>
<%= link_to 'add artist', new_artist_path %>
<hr/>
<h2><%= @artists.length <= 0 ? "No Artist" : "" %></h2>
<ul>
  <% @artists.each do |artist| %>
  <li>
    <%= link_to artist.name, artist %>
  </li>
  <% end %>
</ul>

app/views/artists/show.html.erb
<h1><%= Artists %></h1>
<hr/>
<ul>
  <% @artist.each do |artist| %>
  <li>
    <%= link_to artist.name, artist %>
  </li>
  <% end %>
</ul>
<br>
<br>
<br>
<%= link_to 'Delete artist', @artist, method: :delete, class: 'ui red button inverted' %>

app/views/artists/update.html.erb
<h1>Artists#update</h1>
<p>Find me in app/views/artists/update.html.erb</p>

app/views/billboards/create.html.erb
<h1>Billboards#create</h1>
<p>Find me in app/views/billboards/create.html.erb</p>

app/views/billboards/delete.html.erb
<h1>Billboards#delete</h1>
<p>Find me in app/views/billboards/delete.html.erb</p>

app/views/billboards/edit.html.erb
<h1>Billboards#edit</h1>
<p>Find me in app/views/billboards/edit.html.erb</p>

app/views/billboards/index.html.erb
<h1>Billboards</h1>

<%= link_to 'Create new billboard', new_billboard_path %>

app/views/billboards/show.html.erb
<h1>Billboards#show</h1>
<p>Find me in app/views/billboards/show.html.erb</p>

app/views/billboards/update.html.erb
<h1>Billboards#update</h1>
<p>Find me in app/views/billboards/update.html.erb</p>

app/views/layouts/_navbar.html.erb
<nav>
  <ul>
    <li>
      <%= link_to 'Artists', artists_path %>
    </li>
    <li>
      <%= link_to 'Add an Artist', new_artist_path %>
    </li>
    <li>
      <%= link_to 'Songs', artist_songs_path(:songs) %>
    </li>
    <li>
      <%= link_to 'Add a Song', new_artist_song_path(:artist_id) %>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bilboard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
    <div class="ui container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/songs/delete.html.erb
<h1>Songs#delete</h1>
<p>Find me in app/views/songs/delete.html.erb</p>

app/views/songs/edit.html.erb
<h1>Songs#edit</h1>
<p>Find me in app/views/songs/edit.html.erb</p>

app/views/songs/index.html.erb
<h1>Songs/h1>
<%= link_to 'add songs', new_song_path %>
<hr/>
<h2><%= @songs.length <= 0 ? "No Songs" : "" %></h2>
<ul>
  <% @songs.each do |song| %>
  <li>
    <%= link_to song.name, song %>
  </li>
  <% end %>
</ul>

app/views/songs/new.html.erb
<h1>Songs#new</h1>
<p>Find me in app/views/songs/new.html.erb</p>

app/views/songs/show.html.erb
<h1>Songs</h1>
<hr/>
<ul>
  <% @song.each do |songs| %>
  <li>
    <%= link_to song.name, song %>
  </li>
  <% end %>
</ul>
<br>
<br>
<br>
<%= link_to 'Delete songs', @song, method: :delete, class: 'ui red button inverted' %>